name: property_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0 # أضف هذا السطر
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  modal_progress_hud_nsn: ^0.5.1
  
  shared_preferences: ^2.5.3
  image_picker_web: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sliver.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/pic1.jpg
    - assets/images/pic2.jpg
    - assets/images/sliver.png
    - assets/images/sliver2.png
    - assets/images/pic1.jpg
    - assets/more_Animation.json
    - assets/moer_amolation.json
    - assets/filter_amolation.json
    - assets/complaint.json
    - assets/images/card.jpg
    - assets/images/office.jpg
    - assets/images/off1.jpg
    - assets/images/off2.jpg
    - assets/images/off3.jpg
    - assets/images/init.png
    - assets/images/pic3.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/ReadexPro-VariableFont_HEXP,wght.ttf

