name: property_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0 # أضف هذا السطر
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  modal_progress_hud_nsn: ^0.5.1
  
  shared_preferences: ^2.5.3
  image_picker_web: ^4.0.0
  http_parser: ^4.0.2
  numberpicker: ^2.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.1
  socket_io_client: ^3.1.2
  provider: ^6.1.5+1
  intl: ^0.19.0
  overlay_support: ^2.1.0
  file_picker: ^10.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sliver.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/ReadexPro-VariableFont_HEXP,wght.ttf

